# netlify.toml

[build]
  # Lệnh để Netlify biên dịch code
  command = "npm run build"
  # Thư mục chứa kết quả sau khi biên dịch (Vite mặc định là dist)
  publish = "dist"

[dev]
  command = "npm run dev"

# Quan trọng: Cấu hình này giúp Svelte không bị lỗi 404 khi F5 lại trang
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200